### ISSUE TITLE
Python style

### ISSUE THREAD

**Issue by ksnavely** [kdbartlett/Qweak#1]
One key thing for Python projects is to have a consistent style and stick to well-followed rules from the community.

The widely accepted practice is known as pep8:
  - https://www.python.org/dev/peps/pep-0008/

And luckily there is a nice tool you can use to check your code, also called pep8:
  - https://pypi.python.org/pypi/pep8

Consistency is much better than following every rule. For instance long lines aren't generally bothersome if say, they are under 100 characters, are a URL, best represented in one line, etc.

One thing that stood out to me in your code other than pep8 was you mix CamelCase with snake_case. Once you choose a style, like "all function names are snake cased" you should stick to it. This choice will vary from project to project but the idea is to only use one choice for a given project. That way you can do things like ClassName, SOME_CONST, function_foo, variable_name, etc, and at a glance you know what you are dealing with...it helps the code flow when you start to read through 10k lines and such.

**Comment by kdbartlett** [comment]
Script has been modified to conform to the pep8 style guide. Thanks again for the suggestion.
